### ISSUE TITLE
Support more than URLs

### ISSUE THREAD

**Issue by BenJeau** [rodgomesc/vision-camera-qrcode-scanner#1]
Thanks for this package @rodgomesc! Was wanting a frame processor to scan QR codes and can't believe it's that simple (looking at the source code of this repo). But it seems like it's only supporting URLs for now. I can add the support for it, but can only test for Android as I only have an Linux system.

I'll open a PR with the changes once I'm done with the changes

**Comment by rodgomesc** [comment]
no problem, awesome work , if you don't mind, i'll leave the PR open until i have time to test it on ios too

**Comment by euri10** [comment]
I thought about that at first @rodgomesc but wanted a quick and dirty fix to see if I could read isbn with `react-native-vision-camera` and it's set of plugins !

Unfortunately I didn't see a way in its current api to pass a "constructor" parameter from js/ts to java. I'm no java / react-native guy so I may be completely off on this.

I dont know if having the `barcodeScanner` instantiated for each frame in the callback would be a fast enough solution.

In any case, let me know if you want to keep the lib more focused towards qrcodes detection, I just need a isbn reader for my app and it should be easy to tighten the scope just for that in another lib.
