### ISSUE TITLE
Barcode conversion in javascript instead of native code?

### ISSUE THREAD

**Issue by pke** [rodgomesc/vision-camera-qrcode-scanner#15]
Is there a reason why the conversion of QR content is done in native code?
Couldn't that be done on the plugins JS side as well?

Since the conversion code has to be maintained in Android and iOS doing it in JS would make things easier.

**Comment by rodgomesc** [comment]
well, from my point of view  rarely we will need to make any changes to the conversion logic, and if we were to send this qr code data directly from the native code to javascript anyway we would have to do several type conversions to make the trhough bridge format compatible, wouldn't we?

**Comment by rodgomesc** [comment]
closing due inactivity
