### ISSUE TITLE
QRCode boundingBox and cornerPoints come back undefined on iOS

### ISSUE THREAD

**Issue by chiubaka** [rodgomesc/vision-camera-qrcode-scanner#17]
Looks like we're not getting boundingBox or cornerPoint data back for iOS.

My use case involves showing the user feedback by overlaying the bounding boxes of detected QR codes.

**Comment by chiubaka** [comment]
I'll take a look through the iOS MLKit integration here to see if I can figure out what's going on.

**Comment by chiubaka** [comment]
Ok, looks like `boundingBox` is an Android-only property. However, `cornerPoints` should be provided. I added some logging to the iOS native module and am finding that the `cornerPoints` are defined before they're sent over the bridge.

I think it's likely because there's no conversion to a simple JavaScript-mappable data structure being done on iOS the same way as there is on Android.

I'm going to add that, test it, and then PR it if it works.

**Comment by rodgomesc** [comment]
solved in #18
