### ISSUE TITLE
please also add a barcode reader

### ISSUE THREAD

**Issue by TheEhsanSarshar** [rodgomesc/vision-camera-qrcode-scanner#23]
there is a barcode reader in doc.
but when I install the library there is only a QR code reader

**Comment by rodgomescrn** [comment]
can you be more specific?

**Comment by TheEhsanSarshar** [comment]
how can I scan a barcode.

there is only a scanQrCodes

**Comment by rodgomesc** [comment]
please see https://github.com/rodgomesc/vision-camera-qrcode-scanner/issues/14
