### ISSUE TITLE
update for 0.1.5?

### ISSUE THREAD

**Issue by arnorhs** [rodgomesc/vision-camera-qrcode-scanner#24]
Hey, I'm really interested in the barcode scanner. However the only published module on npm is 0.1.4, which only has the qrcode scanner

**Comment by rodgomescrn** [comment]
yeah, i'll let you know once we have a new release, probably until the end of this week

**Comment by rodgomesc** [comment]
yeah, i'll let you know once we have a new release, probably until the end of this week

**Comment by arnorhs** [comment]
@rodgomesc awesome thanks
