### ISSUE TITLE
Requiring module "node_modules/vision-camera-qrcode-scanner/src/index.ts", which threw an exception: TypeError: global.__reanimatedWorkletInit is not a function. (In 'global.__reanimatedWorkletInit(_f)', 'global.__reanimatedWorkletInit' is undefined) 

### ISSUE THREAD

**Issue by john-mokaied** [rodgomesc/vision-camera-qrcode-scanner#7]
<img width="1313" alt="Screenshot 2021-10-16 at 01 45 56" src="https://user-images.githubusercontent.com/50097658/137564976-480f0496-76cc-4614-8119-399be1328c7b.png">

**Comment by rodgomesc** [comment]
can you just check if you have a `import 'react-native-reanimated';` at the top of  your `tsx` file?

**Comment by yahyamokaied** [comment]
<img width="739" alt="Screenshot 2021-10-16 at 15 16 05" src="https://user-images.githubusercontent.com/50097658/137589036-d5dd93b8-c2aa-4ef3-ac89-081d174acffb.png">

**Comment by yahyamokaied** [comment]
![IMG_3745](https://user-images.githubusercontent.com/50097658/137589075-ab427992-92f8-4693-ac51-1f9f7eb730bb.PNG)

**Comment by yahyamokaied** [comment]
![IMG_3744](https://user-images.githubusercontent.com/50097658/137589077-3919fe6a-2ec8-4573-ac18-68cfd99655eb.PNG)

**Comment by yahyamokaied** [comment]
![IMG_3743](https://user-images.githubusercontent.com/50097658/137589083-32f09ee9-6f22-4c8c-b010-80d23d502fd6.PNG)

**Comment by yahyamokaied** [comment]
<img width="479" alt="Screenshot 2021-10-16 at 15 18 52" src="https://user-images.githubusercontent.com/50097658/137589110-3a3c62c7-b554-485b-85d8-44c14329edcf.png">

**Comment by yahyamokaied** [comment]
<img width="479" alt="Screenshot 2021-10-16 at 15 19 44" src="https://user-images.githubusercontent.com/50097658/137589135-e5bde554-7ee8-4fb7-805f-895aeb288dc0.png">

**Comment by robinsoncol** [comment]
Also ran into this issue

**Comment by robinsoncol** [comment]
Following the [installation instructions](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#android) for react-native-reanimated on android resolved this error on my end. @yahyamokaied
