### ISSUE TITLE
Doesn't supports Barcodes scanning, only scans QR Codes

### ISSUE THREAD

**Issue by Daneyl** [rodgomesc/vision-camera-qrcode-scanner#9]
It seems like this library doesn't support barcodes as I wasn't able to get them scanned through this. However, was able to get QRCodes scanned. Is this true, or I haven't configured this correctly?

**Comment by rodgomesc** [comment]
duplicated  of https://github.com/rodgomesc/vision-camera-qrcode-scanner/issues/1
